--------------- H2 ---------------

drop table if exists oauth_client_details;
create table oauth_client_details (
  client_id VARCHAR(255) PRIMARY KEY,
  resource_ids VARCHAR(255),
  client_secret VARCHAR(255),
  scope VARCHAR(255),
  authorized_grant_types VARCHAR(255),
  web_server_redirect_uri VARCHAR(255),
  authorities VARCHAR(255),
  access_token_validity INTEGER,
  refresh_token_validity INTEGER,
  additional_information VARCHAR(4096),
  autoapprove VARCHAR(255)
);

create table if not exists oauth_client_token (
  token_id VARCHAR(255),
  token LONGVARBINARY,
  authentication_id VARCHAR(255) PRIMARY KEY,
  user_name VARCHAR(255),
  client_id VARCHAR(255)
);

create table if not exists oauth_access_token (
  token_id VARCHAR(255),
  token LONGVARBINARY,
  authentication_id VARCHAR(255) PRIMARY KEY,
  user_name VARCHAR(255),
  client_id VARCHAR(255),
  authentication LONGVARBINARY,
  refresh_token VARCHAR(255)
);

create table if not exists oauth_refresh_token (
  token_id VARCHAR(255),
  token LONGVARBINARY,
  authentication LONGVARBINARY
);

create table if not exists oauth_code (
  code VARCHAR(255), authentication LONGVARBINARY
);

create table if not exists oauth_approvals (
	userId VARCHAR(255),
	clientId VARCHAR(255),
	scope VARCHAR(255),
	status VARCHAR(10),
	expiresAt TIMESTAMP,
	lastModifiedAt TIMESTAMP
);

create table if not exists ClientDetails (
  appId VARCHAR(255) PRIMARY KEY,
  resourceIds VARCHAR(255),
  appSecret VARCHAR(255),
  scope VARCHAR(255),
  grantTypes VARCHAR(255),
  redirectUrl VARCHAR(255),
  authorities VARCHAR(255),
  access_token_validity INTEGER,
  refresh_token_validity INTEGER,
  additionalInformation VARCHAR(4096),
  autoApproveScopes VARCHAR(255)
);

--------------- MySQL ---------------
--drop table if exists oauth_client_details;
--create table oauth_client_details (
--  client_id VARCHAR(255) PRIMARY KEY,
--  resource_ids VARCHAR(255),
--  client_secret VARCHAR(255),
--  scope VARCHAR(255),
--  authorized_grant_types VARCHAR(255),
--  web_server_redirect_uri VARCHAR(255),
--  authorities VARCHAR(255),
--  access_token_validity INTEGER,
--  refresh_token_validity INTEGER,
--  additional_information VARCHAR(4096),
--  autoapprove VARCHAR(255)
--);
--
--create table if not exists oauth_client_token (
--  token_id VARCHAR(255),
--  token LONG VARBINARY,
--  authentication_id VARCHAR(255) PRIMARY KEY,
--  user_name VARCHAR(255),
--  client_id VARCHAR(255)
--);
--
--create table if not exists oauth_access_token (
--  token_id VARCHAR(255),
--  token LONG VARBINARY,
--  authentication_id VARCHAR(255) PRIMARY KEY,
--  user_name VARCHAR(255),
--  client_id VARCHAR(255),
--  authentication LONG VARBINARY,
--  refresh_token VARCHAR(255)
--);
--
--create table if not exists oauth_refresh_token (
--  token_id VARCHAR(255),
--  token LONG VARBINARY,
--  authentication LONG VARBINARY
--);
--
--create table if not exists oauth_code (
--  code VARCHAR(255), authentication LONG VARBINARY
--);
--
--create table if not exists oauth_approvals (
--	userId VARCHAR(255),
--	clientId VARCHAR(255),
--	scope VARCHAR(255),
--	status VARCHAR(10),
--	expiresAt TIMESTAMP,
--	lastModifiedAt TIMESTAMP
--);
--
--create table if not exists ClientDetails (
--  appId VARCHAR(255) PRIMARY KEY,
--  resourceIds VARCHAR(255),
--  appSecret VARCHAR(255),
--  scope VARCHAR(255),
--  grantTypes VARCHAR(255),
--  redirectUrl VARCHAR(255),
--  authorities VARCHAR(255),
--  access_token_validity INTEGER,
--  refresh_token_validity INTEGER,
--  additionalInformation VARCHAR(4096),
--  autoApproveScopes VARCHAR(255)
--);



-- Oracle v11.2.0--
--------------------------------------------------------
--  DDL for Table OAUTH_ACCESS_TOKEN
--------------------------------------------------------
--
--   CREATE TABLE "MINI_PROJECT"."OAUTH_ACCESS_TOKEN"
--    (	"TOKEN_ID" VARCHAR2(255 BYTE),
-- 	"token" BLOB,
-- 	"AUTHENTICATION_ID" VARCHAR2(255 BYTE),
-- 	"USER_NAME" VARCHAR2(255 BYTE),
-- 	"CLIENT_ID" VARCHAR2(255 BYTE),
-- 	"AUTHENTICATION" BLOB,
-- 	"REFRESH_TOKEN" VARCHAR2(255 BYTE)
--    ) SEGMENT CREATION IMMEDIATE
--   PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
--   STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
--   PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
--   TABLESPACE "SYSTEM"
--  LOB ("token") STORE AS BASICFILE (
--   TABLESPACE "SYSTEM" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION
--   NOCACHE LOGGING
--   STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
--   PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT))
--  LOB ("AUTHENTICATION") STORE AS BASICFILE (
--   TABLESPACE "SYSTEM" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION
--   NOCACHE LOGGING
--   STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
--   PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
-- --------------------------------------------------------
-- --  DDL for Table OAUTH_ACTIVE_SESSION
-- --------------------------------------------------------
--
--   CREATE TABLE "MINI_PROJECT"."OAUTH_ACTIVE_SESSION"
--    (	"USERNAME" VARCHAR2(255 BYTE),
-- 	"token" BLOB,
-- 	"CREATED_DATE" TIMESTAMP (6)
--    ) SEGMENT CREATION IMMEDIATE
--   PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
--   STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
--   PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
--   TABLESPACE "SYSTEM"
--  LOB ("token") STORE AS BASICFILE (
--   TABLESPACE "SYSTEM" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION
--   NOCACHE LOGGING
--   STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
--   PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
-- --------------------------------------------------------
-- --  DDL for Table OAUTH_APPROVALS
-- --------------------------------------------------------
--
--   CREATE TABLE "MINI_PROJECT"."OAUTH_APPROVALS"
--    (	"USER_ID" NUMBER(*,0),
-- 	"CLIENT_ID" VARCHAR2(255 BYTE),
-- 	"scope" VARCHAR2(255 BYTE),
-- 	"STATUS" VARCHAR2(10 BYTE),
-- 	"EXPIRESAT" TIMESTAMP (6),
-- 	"LASTMODIFIEDAT" TIMESTAMP (6)
--    ) SEGMENT CREATION IMMEDIATE
--   PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
--   STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
--   PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
--   TABLESPACE "SYSTEM" ;
-- --------------------------------------------------------
-- --  DDL for Table OAUTH_CLIENT_DETAILS
-- --------------------------------------------------------
--
--   CREATE TABLE "MINI_PROJECT"."OAUTH_CLIENT_DETAILS"
--    (	"CLIENT_ID" VARCHAR2(255 BYTE),
-- 	"RESOURCE_IDS" VARCHAR2(255 BYTE),
-- 	"CLIENT_SECRET" VARCHAR2(255 BYTE),
-- 	"SCOPE" VARCHAR2(255 BYTE),
-- 	"AUTHORIZED_GRANT_TYPES" VARCHAR2(255 BYTE),
-- 	"WEB_SERVER_REDIRECT_URI" VARCHAR2(255 BYTE),
-- 	"AUTHORITIES" VARCHAR2(255 BYTE),
-- 	"ACCESS_TOKEN_VALIDITY" NUMBER(10,0),
-- 	"REFRESH_TOKEN_VALIDITY" NUMBER(10,0),
-- 	"ADDITIONAL_INFORMATION" VARCHAR2(4000 BYTE),
-- 	"AUTOAPPROVE" VARCHAR2(255 BYTE)
--    ) SEGMENT CREATION IMMEDIATE
--   PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
--   STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
--   PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
--   TABLESPACE "SYSTEM" ;
-- --------------------------------------------------------
-- --  DDL for Table OAUTH_CLIENT_TOKEN
-- --------------------------------------------------------
--
--   CREATE TABLE "MINI_PROJECT"."OAUTH_CLIENT_TOKEN"
--    (	"TOKEN_ID" VARCHAR2(255 BYTE),
-- 	"token" BLOB,
-- 	"AUTHENTICATION_ID" VARCHAR2(255 BYTE),
-- 	"USER_NAME" VARCHAR2(255 BYTE),
-- 	"CLIENT_ID" VARCHAR2(255 BYTE)
--    ) SEGMENT CREATION IMMEDIATE
--   PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
--   STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
--   PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
--   TABLESPACE "SYSTEM"
--  LOB ("token") STORE AS BASICFILE (
--   TABLESPACE "SYSTEM" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION
--   NOCACHE LOGGING
--   STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
--   PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
-- --------------------------------------------------------
-- --  DDL for Table OAUTH_CODE
-- --------------------------------------------------------
--
--   CREATE TABLE "MINI_PROJECT"."OAUTH_CODE"
--    (	"CODE" VARCHAR2(255 BYTE),
-- 	"AUTHENTICATION" BLOB
--    ) SEGMENT CREATION IMMEDIATE
--   PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
--   STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
--   PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
--   TABLESPACE "SYSTEM"
--  LOB ("AUTHENTICATION") STORE AS BASICFILE (
--   TABLESPACE "SYSTEM" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION
--   NOCACHE LOGGING
--   STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
--   PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
-- --------------------------------------------------------
-- --  DDL for Table OAUTH_REFRESH_TOKEN
-- --------------------------------------------------------
--
--   CREATE TABLE "MINI_PROJECT"."OAUTH_REFRESH_TOKEN"
--    ("TOKEN_ID" VARCHAR2(255 BYTE),
-- 	"token" BLOB,
-- 	"AUTHENTICATION" BLOB
--    ) SEGMENT CREATION IMMEDIATE
--   PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
--   STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
--   PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
--   TABLESPACE "SYSTEM"
--  LOB ("token") STORE AS BASICFILE (
--   TABLESPACE "SYSTEM" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION
--   NOCACHE LOGGING
--   STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
--   PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT))
--  LOB ("AUTHENTICATION") STORE AS BASICFILE (
--   TABLESPACE "SYSTEM" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION
--   NOCACHE LOGGING
--   STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
--   PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;

